spring:
  profiles:
    active: dev
---
uname: lytw13
spring:
  profiles: dev

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #defaultZone: http://eureka01.com:6001/eureka/,http://eureka02.com:6002/eureka/ ,http://eureka03.com:6003/eureka/
  instance:
    hostname: localhost
    ip-address: true
    instance-id: web00

feign:
  hystrix:
    enabled: true
---
uname: lytw13
spring:
  profiles: test

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #defaultZone: http://eureka01.com:6001/eureka/,http://eureka02.com:6002/eureka/ ,http://eureka03.com:6003/eureka/
  instance:
    hostname: localhost
    ip-address: true
    instance-id: web01

feign:
  hystrix:
    enabled: true
